language: cpp
addons:
  apt:
    packages:
      - g++-7
      - clang-6.0
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
matrix:
  include:
    - name: Linux GCC
      os: linux
      dist: xenial
      sudo: required
      before_install:
        - CC=gcc-7 && CXX=g++-7
    - name: Linux Clang
      os: linux
      dist: xenial
      sudo: required
      before_install:
        - CC=clang-6.0 && CXX=clang++-6.0
    - name: Windows
      os: windows
install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -qq update
      sudo apt-get install -y xorg-dev libc++-dev
      wget -q https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.gz
      mkdir vulkan-sdk
      tar -xf vulkan-sdk.tar.gz -C vulkan-sdk
      SDK_VERSION="$(ls vulkan-sdk)"
      export VULKAN_SDK=$(pwd)/vulkan-sdk/$SDK_VERSION/x86_64
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      wget -q https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.zip
      mkdir vulkan-sdk
      7z x vulkan-sdk.zip -ovulkan-sdk
      SDK_VERSION="$(ls vulkan-sdk)"
      export VULKAN_SDK=$(pwd)/vulkan-sdk/$SDK_VERSION/x86_64
      echo "$VULKAN_SDK"
    fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      mkdir build && cd build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install ..
      make -j2 install
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      mkdir build && cd build
      cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=install ..
      msbuild illusion.sln /p:Configuration=Release
    fi
