language: cpp
addons:
  apt:
    packages:
      - g++-7
      - clang-6.0
      - xorg-dev
      - libc++-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
matrix:
  include:
    - name: Linux GCC
      os: linux
      dist: xenial
      sudo: required
      before_install:
        - CC=gcc-7 && CXX=g++-7
    - name: Linux Clang
      os: linux
      dist: xenial
      sudo: required
      before_install:
        - CC=clang-6.0 && CXX=clang++-6.0
    - name: Windows
      os: windows
script:
  - mkdir build && cd build
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install ..; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  make -j2 install; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=install ..; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then msbuild illusion.sln /p:Configuration=Release; fi
