language: cpp
sudo: required
os: linux
dist: trusty
matrix:
  include:
    - name: gcc
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: clang
      addons:
        apt:
          packages:
            - clang-7
          sources:
            - llvm-toolchain-trusty-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xorg-dev
  - wget https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.gz
  - mkdir vulkan-sdk
  - tar -xf vulkan-sdk.tar.gz -C vulkan-sdk
  - SDK_VERSION="$(ls vulkan-sdk)"
  - export VULKAN_SDK=$(pwd)/vulkan-sdk/$SDK_VERSION/x86_64
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install ..
  - make -j2 install
