language: cpp
addons:
  apt:
    packages:
      - g++-7
      - clang-6.0
      - xorg-dev
      - libc++-dev
      - libwayland-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0
  homebrew:
    packages:
      - llvm
matrix:
  include:
    - name: Xenial GCC
      os: linux
      dist: xenial
      sudo: required
      before_script:
        - CC=gcc-7
        - CXX=g++-7
    - name: Xenial Clang
      os: linux
      dist: xenial
      sudo: required
      before_script:
        - CC=clang-6.0
        - CXX=clang++-6.0
    - name: Windows
      os: windows
      install:
        - choco install python3
    - name: OS X
      os: osx
script:
  - mkdir build && cd build
  - find /usr/local/opt/llvm/lib
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake ..; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake -DCMAKE_CXX_FLAGS=-I/usr/local/opt/llvm/include/c++/v1\ -L/usr/local/opt/llvm/lib ..; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake -G "Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=/c/Python37/python.exe ..; fi
  - cmake --build .
